# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-21 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0002_remove_action_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='read',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
